Fix Get-RscMssqlInstance
rubrikinc/rubrik-powershell-sdk pull request #167
Opened 2024-12-20 22:57 UTC by jakerobinson

Fix Get-RscMssqlInstance fields to account for API changes, fixed tests, added tests

2025-01-15 07:06 UTC, guirava requested changes

2025-01-15 07:06 UTC, guirava commented on Toolkit/Public/Get-RscMssqlInstance.ps1
> +                $nameFilter.texts = $HostName
`texts` is a list of strings, but `$HostName` is a string. 
Using `get-rsctype` helps with finding typing issues like that: `Get-RscType` generates an error when trying to assign a wrong type:

```
> get-rsctype -Name Filter -InitialValues @{"Field"=[RubrikSecurityCloud.Types.HierarchyFilterField]::NAME_EXACT_MATCH ;
>> "Texts"= $HostName }
Get-RscType: Provided value of input field Texts is wrong type: System.ArgumentException: Object of type 'System.String' cannot be converted to type 'System.Collections.Generic.List`1[System.String]'.
```

so instead of `New-Object`: 
shorter and safer:

```
$nameFilter = Get-RscType -Name Filter -InitialValues @{
  "Field" = [RubrikSecurityCloud.Types.HierarchyFilterField]::NAME_EXACT_MATCH;
  "Texts" = @($HostName)
}
```

2025-01-15 17:06 UTC, jakerobinson commented on Toolkit/Public/Get-RscMssqlInstance.ps1
> +            if ( $AsQuery ) {
I don't think I can do this. I have to be explicit in the fields we get back due to the possibility of retrieving fields that are not fully implemented.

2025-01-15 17:23 UTC, jakerobinson commented on Toolkit/Public/Get-RscMssqlInstance.ps1
> +            if ( $AsQuery ) {
Confirmed. Using `-AddField` overfetches when all I need are the name and ID.

2025-01-15 20:40 UTC, guirava commented on Toolkit/Public/Get-RscMssqlInstance.ps1
> +            if ( $AsQuery ) {
Now besides maintaining autofield,
I could see how you just want to select 2 fields, you can do:

```
$query.Field.Cluster = Get-RscType -Name Cluster -InitialProperties Name,Id
```

2025-01-15 20:47 UTC, guirava commented on Toolkit/Public/Get-RscMssqlInstance.ps1
> +            if ( $AsQuery ) {
The motivation for using `Get-RscType` is this:

1. it can catch type mismatches
2. it creates much shorter code
3. especially this: your approach with ` = "FETCH"` is correct , but it is based on a specific implementation: fields that are not null need to be retrieved. It's all fine for you and me , but these toolkit scripts are going to be *the reference use* of the SDK, so we want to minimize exposing implementation choices. The user now has to understand our implementation choices. When you say `-InitialProperties Name,Id`  it states the fields you want, it doesn't state the mechanism for retrieving them. 

I'm also thinking big picture: the PowerShell toolkit scripts are going to be the reference even for other SDKs. If we implement SDKs that don't use the null-field mechanism, then toolkit scripts from an SDK to another will look different. If we use a descriptive method like `Get-RscType` to just say what fields you want, then it is a lot more portable across SDKs.

2025-01-15 21:14 UTC, jakerobinson commented on Toolkit/Public/Get-RscMssqlInstance.ps1
> +            if ( $AsQuery ) {
`IsTprEnabled` is one example. The point though is that I can't babysit that, so it's easier to fetch just the fields that users are asking for. Still dreaming of a lazy-load feature. 😂

2025-01-16 02:21 UTC, guirava approved these changes

2025-01-16 02:22 UTC, merged